---

- name: Setup PHP Source and AFL for Fuzzing
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all, localhost
  vars:
    php_src_folder: /root/php-src
    php_src_repo: https://github.com/php/php-src.git
  tasks:

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install screen
      apt:
        name: screen
        state: present

    - name: Install American Fuzzy Lop
      apt:
        name: afl
        state: present

    - name: Install PHP build dependencies
      apt:
        pkg:
          - pkg-config
          - build-essential
          - autoconf
          - bison
          - re2c
          - libxml2-dev
          - libsqlite3-dev
          - libbz2-dev
        state: present
        update_cache: true

    - name: Clone PHP source
      git:
        repo: "{{ php_src_repo }}"
        dest: "{{ php_src_folder }}"
        update: yes

    - name: Run buildconf
      command: ./buildconf
      args:
        chdir: "{{ php_src_folder }}"

    - name: Get AFL Injection Location
      shell: "grep -n \"case PHP_MODE_CLI_DIRECT:\" sapi/cli/php_cli.c | cut -f1 -d:"
      args:
        chdir: "{{ php_src_folder }}"
      register: injection_pre_loc

    - name: Increment injection point
      shell: "echo $(({{ injection_pre_loc.stdout }} + 2))"
      register: injection_loc

    - name: Inject AFL into PHP
      shell: "awk -v n={{ injection_loc.stdout }} -v s=\"\t\t\t__AFL_INIT();\n\t\t\twhile (__AFL_LOOP(100000))\" 'NR == n {print s} {print}' sapi/cli/php_cli.c > sapi/cli/php_cli.c.new"
      args:
        chdir: "{{ php_src_folder }}"

    - name: Replace php_cli.c
      shell: "mv sapi/cli/php_cli.c.new sapi/cli/php_cli.c"
      args:
        chdir: "{{ php_src_folder }}"

    - name: Configure PHP
      shell: "CC=afl-clang-fast CXX=afl-clang-fast++ ./configure --with-bz2 --enable-exif"
      args:
        chdir: "{{ php_src_folder }}"

    - name: Make PHP
      shell: "AFL_USE_ASAN=1 make"
      args:
        chdir: "{{ php_src_folder }}"
